# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
    ]
