# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180110_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель'},
        ),
    ]
