# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_price_after_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_after_discount',
            new_name='price_with_discount',
        ),
    ]
