# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_auto_20180115_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlisted',
            field=models.ManyToManyField(related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
