# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
