# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180117_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='product',
            name='wishlisted',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='В избранном'),
        ),
    ]
