# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180126_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.IntegerField(default=0, verbose_name='Цена со скидкой'),
        ),
    ]
