# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180126_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
    ]
