# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20180126_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.IntegerField(verbose_name='Цена со скидкой'),
        ),
    ]
