# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20180126_1905'),
        ('shop', '0015_auto_20180117_1257'),
    ]

    operations = [
    ]
