# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_merge_20180127_1940'),
        ('shop', '0031_merge_20180127_2040'),
    ]

    operations = [
    ]
